name: latentafis
channels:
  - conda-forge
  - defaults
dependencies:
  - gdb=8.2=py27h4bd59f5_0
  - libgfortran=3.0.0=1
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports.weakref=1.0rc1=py27_0
  - backports_abc=0.5=py27h7b3c97b_0
  - blas=1.0=mkl
  - bleach=1.5.0=py27_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.10.15=py27_0
  - cffi=1.11.5=py27he75722e_1
  - cloudpickle=0.6.1=py27_0
  - configparser=3.5.0=py27h5117587_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cycler=0.10.0=py27_0
  - dask-core=0.20.2=py27_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py27_0
  - entrypoints=0.2.3=py27_2
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fastcache=1.0.2=py27h14c3975_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - funcsigs=1.0.2=py27h83f16ab_0
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py27h10f8cd9_2
  - graphite2=1.3.12=h23475e2_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py27h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - html5lib=0.9999999=py27_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.4.1=py27_0
  - intel-openmp=2019.1=144
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27h89fb69b_0
  - ipywidgets=7.4.2=py27_0
  - jasper=2.0.14=h07fcdf6_1
  - jinja2=2.10=py27_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py27h7ed5aa4_0
  - jupyter=1.0.0=py27_7
  - jupyter_client=5.2.3=py27_0
  - jupyter_console=5.2.0=py27_1
  - jupyter_core=4.4.0=py27_0
  - keras=2.2.0=0
  - keras-applications=1.0.2=py27_0
  - keras-base=2.2.0=py27_0
  - keras-preprocessing=1.0.1=py27_0
  - kiwisolver=1.0.1=py27hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.35=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - linecache2=1.0.0=py27_0
  - llvmlite=0.25.0=py27hd408876_0
  - markdown=3.0.1=py27_0
  - markupsafe=1.1.0=py27h7b6447c_0
  - matplotlib=2.2.2=py27hb69df0a_2
  - mistune=0.8.4=py27h7b6447c_0
  - mkl=2018.0.3=1
  - mock=2.0.0=py27h0c0c831_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.0.0=py27_2
  - nbconvert=5.3.1=py27_0
  - nbformat=4.4.0=py27hed7f2b2_0
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.2=py27_1
  - ninja=1.8.2=py27h6bb024c_1
  - notebook=5.7.2=py27_0
  - numba=0.40.0=py27h962f231_0
  - numpy=1.12.1=py27h9378851_1
  - olefile=0.46=py27_0
  - opencv=3.4.2=py27h6fd60c2_1
  - openssl=1.1.1a=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py27_1
  - pathlib2=2.3.2=py27_0
  - pbr=5.1.1=py27_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pillow=5.3.0=py27h34e0f95_0
  - pip=18.1=py27_0
  - pixman=0.34.0=hceecf20_3
  - prometheus_client=0.4.2=py27_0
  - prompt_toolkit=1.0.15=py27h1b593e1_0
  - protobuf=3.6.1=py27he6710b0_0
  - psutil=5.4.8=py27h7b6447c_0
  - ptyprocess=0.6.0=py27_0
  - py-opencv=3.4.2=py27hb342d67_1
  - pycparser=2.19=py27_0
  - pygments=2.2.0=py27_0
  - pyparsing=2.3.0=py27_0
  - pyqt=5.6.0=py27_2
  - python=2.7.15=h9bab390_4
  - python-dateutil=2.7.5=py27_0
  - pytorch=0.4.0=py27hdf912b8_0
  - pytz=2018.7=py27_0
  - pywavelets=1.0.1=py27hdd07704_0
  - pyyaml=3.13=py27h14c3975_0
  - pyzmq=17.1.2=py27h14c3975_0
  - qt=5.6.3=h8bf5577_3
  - qtconsole=4.4.2=py27_0
  - readline=7.0=h7b6447c_5
  - scandir=1.9.0=py27h14c3975_0
  - scikit-image=0.14.0=py27hf484d3e_1
  - scikit-learn=0.20.1=py27h4989274_0
  - scipy=1.1.0=py27hd20e5f9_0
  - send2trash=1.5.0=py27_0
  - setuptools=40.6.2=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.18.1=py27hf484d3e_2
  - six=1.11.0=py27_1
  - spyder-kernels=0.2.6=py27_0
  - sqlite=3.25.3=h7b6447c_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - sympy=1.3=py27_0
  - tensorflow=1.3.0=0
  - tensorflow-base=1.3.0=py27h0dbb4d0_1
  - tensorflow-tensorboard=1.5.1=py27hf484d3e_1
  - terminado=0.8.1=py27_1
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py27_0
  - torchvision=0.2.1=py27_0
  - tornado=5.1.1=py27h7b6447c_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.2=py27_0
  - unittest2=1.1.0=py27_0
  - wcwidth=0.1.7=py27h9e3e1ab_0
  - werkzeug=0.14.1=py27_0
  - wheel=0.32.3=py27_0
  - widgetsnbextension=3.4.2=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
